version: '2.0'

services:
  node1.onezone.localhost:
    image: onedata/onezone:3.0.0-RC3
    hostname: node1.onezone.localhost
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: onezone-1
    volumes:
        # - "${AUTH_PATH}:/volumes/persistence/var/lib/oz_worker/auth.config"
        - "${ONEZONE_CONFIG_DIR}:/volumes/persistence"
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "80:80"
      - "5555:5555"
      - "5556:5556"
      - "6665:6665"
      - "6666:6666"
      - "7443:7443"
      - "8443:8443"
      - "8876:8876"
      - "8877:8877"
      - "9443:9443"
    environment:
      ONEPANEL_BATCH_MODE: "true"
      ONEZONE_CONFIG: |
        cluster:
          domainName: "onezone.localhost"
          autoDeploy: true
          nodes:
            n1:
              hostname: "node1"
          managers:
            mainNode: "n1"
            nodes:
              - "n1"
          workers:
            nodes:
              - "n1"
          databases:
            nodes:
              - "n1"
        onezone:
          name: "Example"
          domainName: "onezone.localhost"
        onepanel:
          users:
            "admin":
              password: "Password1"
              userRole: "admin"
            "user":
              password: "Password2"
              userRole: "regular"
