version: '2.0'

services:
  node1.oneprovider.localhost:
    image: onedata/oneprovider:3.0.0-RC3
    hostname: node1.oneprovider.localhost
    # dns: 8.8.8.8 # uncomment if container can't ping any domain
    container_name: oneprovider-1
    volumes:
        - "${ONEPROVIDER_CONFIG_DIR}:/volumes/persistence"
        - "${ONEPROVIDER_DATA_DIR}:/volumes/storage"
        - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - scenario2


networks:
  scenario2:
